# Generated by Django 4.0.6 on 2022-08-02 22:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_loggedexercise_last_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='rep_ranges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None),
        ),
    ]
